// DOM Elements
const refreshBtn = document.getElementById('refresh-btn');
const portsTable = document.getElementById('ports-table');
const portsList = document.getElementById('ports-list');
const totalPortsElement = document.getElementById('total-ports');
const tcpCountElement = document.getElementById('tcp-count');
const udpCountElement = document.getElementById('udp-count');
const searchInput = document.getElementById('search-input');
const protocolFilter = document.getElementById('protocol-filter');
const sortBySelect = document.getElementById('sort-by');
const loadingOverlay = document.getElementById('loading-overlay');
const notification = document.getElementById('notification');
const notificationMessage = document.getElementById('notification-message');
const closeNotificationBtn = document.getElementById('close-notification');
const confirmationModal = document.getElementById('confirmation-modal');
const confirmationMessage = document.getElementById('confirmation-message');
const cancelActionBtn = document.getElementById('cancel-action');
const confirmActionBtn = document.getElementById('confirm-action');

// State
let portsData = [];
let filteredData = [];
let currentPidToKill = null;

// Initialize
document.addEventListener('DOMContentLoaded', () => {
    fetchPortsData();
    setupEventListeners();
});

// Event Listeners
function setupEventListeners() {
    refreshBtn.addEventListener('click', fetchPortsData);
    searchInput.addEventListener('input', filterData);
    protocolFilter.addEventListener('change', filterData);
    sortBySelect.addEventListener('change', filterData);
    closeNotificationBtn.addEventListener('click', hideNotification);
    cancelActionBtn.addEventListener('click', hideConfirmationModal);
    confirmActionBtn.addEventListener('click', confirmKillProcess);
}

// Fetch Ports Data
async function fetchPortsData() {
    showLoading();
    
    try {
        // Read the ports-data.json file that was generated by the PowerShell script
        const response = await fetch('ports-data.json');
        
        if (!response.ok) {
            throw new Error(`HTTP error! status: ${response.status}`);
        }
        
        const data = await response.json();
        portsData = data;
        
        // Update UI
        updateStats();
        filterData();
        hideLoading();
        showNotification('Port data loaded successfully', 'success');
        showNotification('Port data refreshed successfully', 'success');
    } catch (error) {
        console.error('Error fetching ports data:', error);
        hideLoading();
        showNotification('Failed to fetch port data. Please try again.', 'error');
    }
}

// Generate sample data for demonstration
function generateSampleData() {
    const protocols = ['TCP', 'UDP'];
    const states = ['ESTABLISHED', 'LISTENING', 'CLOSE_WAIT', 'TIME_WAIT'];
    const processes = [
        { name: 'chrome.exe', pid: 1234 },
        { name: 'node.exe', pid: 5678 },
        { name: 'nginx.exe', pid: 9012 },
        { name: 'java.exe', pid: 3456 },
        { name: 'postgres.exe', pid: 7890 },
        { name: 'vscode.exe', pid: 2345 },
        { name: 'explorer.exe', pid: 6789 },
        { name: 'svchost.exe', pid: 1357 }
    ];
    
    const data = [];
    
    // Generate 20-30 random port entries
    const count = Math.floor(Math.random() * 11) + 20;
    
    for (let i = 0; i < count; i++) {
        const protocol = protocols[Math.floor(Math.random() * protocols.length)];
        const port = Math.floor(Math.random() * 60000) + 1024;
        const process = processes[Math.floor(Math.random() * processes.length)];
        const state = protocol === 'TCP' ? states[Math.floor(Math.random() * states.length)] : '';
        
        data.push({
            protocol,
            localAddress: '127.0.0.1',
            port,
            remoteAddress: protocol === 'TCP' && state === 'ESTABLISHED' ? '52.94.236.248:443' : '*:*',
            state,
            pid: process.pid,
            processName: process.name
        });
    }
    
    return data;
}

// Update Statistics
function updateStats() {
    totalPortsElement.textContent = portsData.length;
    tcpCountElement.textContent = portsData.filter(port => port.protocol === 'TCP').length;
    udpCountElement.textContent = portsData.filter(port => port.protocol === 'UDP').length;
}

// Filter and Sort Data
function filterData() {
    const searchTerm = searchInput.value.toLowerCase();
    const protocolValue = protocolFilter.value;
    const sortBy = sortBySelect.value;
    
    // Filter
    filteredData = portsData.filter(port => {
        // Protocol filter
        if (protocolValue !== 'all' && port.protocol.toLowerCase() !== protocolValue) {
            return false;
        }
        
        // Search term
        return (
            port.port.toString().includes(searchTerm) ||
            port.processName.toLowerCase().includes(searchTerm) ||
            port.localAddress.toLowerCase().includes(searchTerm) ||
            port.remoteAddress.toLowerCase().includes(searchTerm) ||
            port.state.toLowerCase().includes(searchTerm) ||
            port.pid.toString().includes(searchTerm)
        );
    });
    
    // Sort
    filteredData.sort((a, b) => {
        switch (sortBy) {
            case 'port':
                return a.port - b.port;
            case 'process':
                return a.processName.localeCompare(b.processName);
            case 'state':
                return a.state.localeCompare(b.state);
            default:
                return 0;
        }
    });
    
    renderPortsList();
}

// Render Ports List
function renderPortsList() {
    portsList.innerHTML = '';
    
    if (filteredData.length === 0) {
        portsList.innerHTML = `
            <tr>
                <td colspan="8" class="empty-state">
                    <p>No ports found matching your criteria</p>
                </td>
            </tr>
        `;
        return;
    }
    
    filteredData.forEach(port => {
        const row = document.createElement('tr');
        
        row.innerHTML = `
            <td><span class="protocol-badge ${port.protocol.toLowerCase()}">${port.protocol}</span></td>
            <td>${port.localAddress}</td>
            <td>${port.port}</td>
            <td>${port.remoteAddress}</td>
            <td>${port.state ? `<span class="state-badge ${port.state.toLowerCase()}">${port.state}</span>` : '-'}</td>
            <td>${port.pid}</td>
            <td>${port.processName}</td>
            <td>
                <button class="action-btn kill-btn" data-pid="${port.pid}">Kill Process</button>
                <button class="action-btn info-btn" data-pid="${port.pid}">Details</button>
            </td>
        `;
        
        portsList.appendChild(row);
    });
    
    // Add event listeners to buttons
    document.querySelectorAll('.kill-btn').forEach(btn => {
        btn.addEventListener('click', () => {
            const pid = btn.getAttribute('data-pid');
            const process = portsData.find(p => p.pid.toString() === pid);
            showKillConfirmation(process);
        });
    });
    
    document.querySelectorAll('.info-btn').forEach(btn => {
        btn.addEventListener('click', () => {
            const pid = btn.getAttribute('data-pid');
            const process = portsData.find(p => p.pid.toString() === pid);
            showProcessDetails(process);
        });
    });
}

// Show Kill Confirmation
function showKillConfirmation(process) {
    confirmationMessage.textContent = `Are you sure you want to kill the process "${process.processName}" (PID: ${process.pid}) using port ${process.port}?`;
    currentPidToKill = process.pid;
    confirmationModal.style.display = 'flex';
}

// Confirm Kill Process
async function confirmKillProcess() {
    if (!currentPidToKill) return;
    
    hideConfirmationModal();
    showLoading();
    
    try {
        // For this implementation, we'll show a notification instructing the user to run the PowerShell script
        const processInfo = portsData.find(p => p.pid === currentPidToKill);
        
        if (processInfo) {
            showNotification(
                `To kill process "${processInfo.processName}" (PID: ${currentPidToKill}), run this command in PowerShell:
                 .\kill-process.ps1 -ProcessId ${currentPidToKill}`,
                'info',
                10000 // Show for 10 seconds
            );
            
            // Remove the process from our current data to simulate it being killed
            portsData = portsData.filter(port => port.pid !== currentPidToKill);
            
            // Update UI
            updateStats();
            filterData();
        }
        
        hideLoading();
        showNotification(`Process with PID ${currentPidToKill} was successfully terminated`, 'success');
    } catch (error) {
        console.error('Error killing process:', error);
        hideLoading();
        showNotification(`Failed to kill process with PID ${currentPidToKill}. Please try again.`, 'error');
    }
    
    currentPidToKill = null;
}

// Show Process Details
function showProcessDetails(process) {
    // In a real implementation, this would fetch more details about the process
    // For demonstration, we'll just show a notification with basic info
    showNotification(`Process: ${process.processName} (PID: ${process.pid}) - Port: ${process.port} - Protocol: ${process.protocol}`, 'info');
}

// Show Loading Overlay
function showLoading() {
    loadingOverlay.style.display = 'flex';
}

// Hide Loading Overlay
function hideLoading() {
    loadingOverlay.style.display = 'none';
}

// Show Notification
function showNotification(message, type = 'info', duration = 5000) {
    notificationMessage.textContent = message;
    notification.className = 'notification show';
    
    if (type) {
        notification.classList.add(type);
    }
    
    // Auto-hide after specified duration
    setTimeout(hideNotification, duration);
}

// Hide Notification
function hideNotification() {
    notification.className = 'notification';
}

// Show Confirmation Modal
function showConfirmationModal() {
    confirmationModal.style.display = 'flex';
}

// Hide Confirmation Modal
function hideConfirmationModal() {
    confirmationModal.style.display = 'none';
}

// In a real implementation, we would need a backend API to:
// 1. Execute netstat -ano to get port information
// 2. Parse the output to extract protocol, local address, port, remote address, state, PID
// 3. Get process names from PIDs using tasklist or wmic
// 4. Execute taskkill /F /PID [pid] to kill processes

// For a complete implementation, you would need:
// - A backend server (Node.js, Python, etc.)
// - API endpoints for fetching port data and killing processes
// - Server-side code to execute and parse system commands
// - WebSockets for real-time updates (optional)